### PR TITLE
Update bm_quickpay.php

### PR DESCRIPTION
**Pull request by boelle**
i hope that it includes the rest of the files in the same PR

doing this over the web interface

### CODE REVIEW

**Review by BrockleyJohn — COMMENTED** [review]
MODULE_BOXES_QUICKPAY_DESCRIPTION is used in admin / modules / boxes / bm_quickpay to describe the module to the administrator. Do you think 'we accept' will make sense in that context?

**Comment by BrockleyJohn** [comment]
there seems only to be one file in this pr

**Comment by boelle** [comment]
yep still editing the next one so there is only one file so far... i hope they are added as i get along

**Comment by boelle** [comment]
will translate the admin folder now

there should be 2 files in the pr so my assumption that they are added as i go seems to be correct

**Comment by boelle** [comment]
just looked briefly and admin folder seems ok with the danish language

**Comment by boelle** [comment]
admin / modules / boxes / bm_quickpay ??

i assume you mean: /includes/languages/danish/modules/boxes/bm_quickpay.php ?

**Pull request merged**
